<style type="text/css">
.col3-layout .col-wrapper .col-main{
    float: left;
}

.container{
  display: flex;
}

.card {
  height: 300px;
}

</style>
<div class="container">
  <?php foreach ($this->getCollection() as $data): ?>
    <img src="<?php echo $this->getBaseUrl().'media'.DS.'brand'.DS.'banner'.DS.$data->banner; ?>" style="width:100%">
  <?php endforeach ?>
</div>


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
        integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="style.css">

<style type="text/css">
* {
    margin: 0;
    padding: 0;
    font-family: sans-serif;
}
  
.feature{
    margin-bottom: 100px;
}
.item8{
    margin: 25px 25px;
    display: grid;
    grid-template-columns: 1fr 1fr 1fr 1fr;
    gap: 10px 2em;
}
.item8_div1{
  width: 300px;
    border-radius: 2%;
    background-color: #ebebeb;
    margin-top: 20px;
    height: 300px;
    box-shadow: 2px 2px 2px 2px #a4a3a3;
}
.item8 .img {
    height: 70%;
}
.item8 .img img{
    display: block;
    margin-top: auto;
    margin-right: auto;
    margin-left: auto;
    width: 100%;
    height: 100%;
}
.item8 .caption {
    display: flex;
    margin-top: 15px;
    /* flex-direction: column; */
    justify-content: center;
    align-items: center;
}
.item8_div2{
    display: flex;
    justify-content: center;
    align-items: center;
    margin-top: 60px;
}
.item8_div2 a{
    text-decoration: none;
    font-size: 20px;
    font-weight: 600;
    color: #0E259A;
    margin-right: 10px;
}
</style>

<div class="feature">
    <div>
        <div class="title">
            <h2>Products</h2>
        </div>
    </div>
    <div class="item8">
      <?php foreach ($this->getProduct() as $data): ?>
        <a href="<?php echo $this->getBaseUrl().'brand'.DS.str_replace(' ','-',strtolower($data->name)).'.html'; ?>">
          <div class="item8_div1">
              <div class="img">
                <img src="<?php echo $this->getBaseUrl().'media'.DS.'catalog/product'.$data->getImage(); ?>">
              </div>
              <div class="caption">
                  <h1><?php echo $data->name; ?></h1>
              </div>
          </div>
        </a>
      <?php endforeach ?>
    </div>
</div>
