<?php $categories = $this->getCategory();?>
<style type="text/css">
.category-div{
    margin-top: 450px;
}

</style>
<div class="category-div">
    <section id="sidebar">
        <div>
            <h6 class="p-1 border-bottom">CATRGORIES</h6>
            
            <ul>
                <?php foreach ($categories as $category):?>
                    <li>
                        <a href="<?php echo Mage::getUrl('', array('_current' => true, '_use_rewrite' => true, '_query' => array('cat' => $category->getId()))); ?>">
                            <?php echo $category->getName() ?>
                        </a>
                    </li>
                <?php endforeach ?>
            </ul>
        </div>
    </section>
</div>