<table border="1" style="border-collapse: collapse; width: 100%;">
    <thead>
        <th>Name</th>
        <th>Desccription</th>
        <th>Grid</th>
        <th>Query</th>
    </thead>

    <tr>
        <td>One</td>
        <td>Need a list of product with these columns product name, sku, cost, price, color.</td>
        <td><a href="<?php echo $this->getBaseUrl().'practice/adminhtml_query/one' ?>">Grid</a></td>
        <td><a href="<?php echo $this->getBaseUrl().'practice/adminhtml_query/one' ?>">Query</a></td>
    </tr>
</table>